# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rover-ESP32' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rover-ESP32
    pod 'CocoaMQTT'	
end
